# Generated by Django 2.1.5 on 2019-01-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cl',
            field=models.CharField(default=1, max_length=36),
        ),
    ]
